version: "3.8"
services:
  app:
    build:
      context: ./app
    environment:
      DSN: "dbname=${DB_NAME?DB_NAME} user=${DB_USER?DB_USER} password=${DB_PASS?DB_PASS} host=${DB_HOST?DB_HOST}"
    depends_on:
      - db
    volumes:
      - ./app:/src

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "${DB_NAME?DB_NAME}"
      POSTGRES_USER: "${DB_USER?DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS?DB_PASS}"
